[app]
env = "production"
scheme = "http"
host = "aitheria.com"
port = 8000
version = "0.0.1"

[db]
username = "user"
password = "password"
host = "0.0.0.0"
port = 5432
name = "project"

[log]
level = "info"

[google]
client_id = "931375941509-4bvpoo37t11r8g2ivif564p867t44927.apps.googleusercontent.com"
client_secret = "ZKVuAm0ejYqZ1l03WzCXlHT_"