[app]
env = "production"
scheme = "http"
host = "aitheria.com"
port = 8000
version = "0.0.1"
api_key = "FFF9807D-A576-4F29-A7C0-5BA493F63E78"

[db]
username = "user"
password = "password"
host = "0.0.0.0"
port = 5432
name = "project"

[log]
level = "info"

[jwt]
secret_key = "D56D60EC-75C7-4A1F-A1FA-5D7350DB8CFC"

[google]
client_id = "931375941509-4bvpoo37t11r8g2ivif564p867t44927.apps.googleusercontent.com"
client_secret = "ZKVuAm0ejYqZ1l03WzCXlHT_"